"""Shared foundations for provider-neutral Indian language operations."""

from importlib.metadata import PackageNotFoundError, version

try:
    __version__ = version("indic-language-utils")
except PackageNotFoundError:  # pragma: no cover - source tree without installation
    __version__ = "0.0.0"

from .bhashini import BhashiniConfig, BhashiniDetectionProvider, BhashiniTranslationProvider
from .cache import CacheKeyBuilder, MemoryCache, NullCache, SingleFlight, SQLiteCache
from .config import (
    CacheSettings,
    ProviderSettings,
    RetrySettings,
    Secret,
    Settings,
    TelemetrySettings,
)
from .detection import (
    DetectionClient,
    DetectionOptions,
    DetectionProvider,
    DetectionProviderMetadata,
    DetectionRequest,
    DetectionResult,
    DetectionResultCodec,
    FastTextDetectionConfig,
    FastTextDetectionProvider,
    LanguageCandidate,
    ProviderDetectionResult,
    SyncDetectionClient,
    create_detection_cache,
    detect,
    detect_batch,
    detect_batch_sync,
    detect_script,
    detect_sync,
    get_detection_client,
    get_sync_detection_client,
)
from .errors import LanguageUtilsError
from .google_translate import (
    GoogletransConfig,
    GoogleTranslateConfig,
    GoogleTranslateProvider,
    GoogletransTranslationProvider,
)
from .languages import DEFAULT_LANGUAGE_REGISTRY, LanguageRegistry, LanguageTag
from .models import (
    CacheMetadata,
    ExecutionTiming,
    ModelIdentity,
    OperationContext,
    ProviderIdentity,
    WarningInfo,
)
from .processors import ProcessorIdentity, VersionedProcessor
from .providers import CapabilityDeclaration, CapabilityId, ProviderRegistry
from .routing import OrderedRouter, RouteCandidate, RouteRequirement
from .translation import (
    DEFAULT_TRANSLATION_PROCESSORS,
    CatalogEntry,
    CatalogStatus,
    DefaultTranslationStructureProcessor,
    LocalizationCatalog,
    PreparedText,
    ProtectedContentProcessor,
    Segment,
    SyncTranslationClient,
    TextFormat,
    TranslationClient,
    TranslationOptions,
    TranslationProcessorPipeline,
    TranslationRequest,
    TranslationResult,
    TranslationResultCodec,
    TranslationSegmentProcessor,
    TranslationStructureProcessor,
    UnicodeNormalizationProcessor,
    create_translation_cache,
    get_sync_translation_client,
    get_translation_client,
    translate,
    translate_batch,
    translate_batch_sync,
    translate_sync,
)

__all__ = [
    "DEFAULT_LANGUAGE_REGISTRY",
    "DEFAULT_TRANSLATION_PROCESSORS",
    "BhashiniConfig",
    "BhashiniDetectionProvider",
    "BhashiniTranslationProvider",
    "CacheKeyBuilder",
    "CacheMetadata",
    "CacheSettings",
    "CapabilityDeclaration",
    "CapabilityId",
    "CatalogEntry",
    "CatalogStatus",
    "DefaultTranslationStructureProcessor",
    "DetectionClient",
    "DetectionOptions",
    "DetectionProvider",
    "DetectionProviderMetadata",
    "DetectionRequest",
    "DetectionResult",
    "DetectionResultCodec",
    "ExecutionTiming",
    "FastTextDetectionConfig",
    "FastTextDetectionProvider",
    "GoogleTranslateConfig",
    "GoogleTranslateProvider",
    "GoogletransConfig",
    "GoogletransTranslationProvider",
    "LanguageCandidate",
    "LanguageRegistry",
    "LanguageTag",
    "LanguageUtilsError",
    "LocalizationCatalog",
    "MemoryCache",
    "ModelIdentity",
    "NullCache",
    "OperationContext",
    "OrderedRouter",
    "PreparedText",
    "ProcessorIdentity",
    "ProtectedContentProcessor",
    "ProviderDetectionResult",
    "ProviderIdentity",
    "ProviderRegistry",
    "ProviderSettings",
    "RetrySettings",
    "RouteCandidate",
    "RouteRequirement",
    "SQLiteCache",
    "Secret",
    "Segment",
    "Settings",
    "SingleFlight",
    "SyncDetectionClient",
    "SyncTranslationClient",
    "TelemetrySettings",
    "TextFormat",
    "TranslationClient",
    "TranslationOptions",
    "TranslationProcessorPipeline",
    "TranslationRequest",
    "TranslationResult",
    "TranslationResultCodec",
    "TranslationSegmentProcessor",
    "TranslationStructureProcessor",
    "UnicodeNormalizationProcessor",
    "VersionedProcessor",
    "WarningInfo",
    "__version__",
    "create_detection_cache",
    "create_translation_cache",
    "detect",
    "detect_batch",
    "detect_batch_sync",
    "detect_script",
    "detect_sync",
    "get_detection_client",
    "get_sync_detection_client",
    "get_sync_translation_client",
    "get_translation_client",
    "translate",
    "translate_batch",
    "translate_batch_sync",
    "translate_sync",
]
